---
- name: ensure upstream repository key is added
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"

- name: apt | Ensure upstream repository is configured
  become: true
  apt_repository:
    repo: "deb [arch=amd64,i386,ppc64el] http://mirror.netcologne.de/mariadb/repo/10.1/ubuntu xenial main"

- name: apt | Ensure packages are installed
  become: true
  package:
    name: "{{ item }}"
  with_items: 
    - mariadb-server
    - mariadb-client
    - python-mysqldb
  register: deb_mariadb_install_packages