---
- include: install.yml

- name: Check if MySQL packages were installed.
  set_fact:
    mariadb_install_packages: "{{ deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed }}"

- include: config.yml
- include: initdb.yml
